"""
pdf_report.py -- Automated PDF Incident Report Generator
=========================================================
Part of Aqua-Sentinel AI: Hierarchical Geo-Intelligent Framework for
Real-Time Multi-Spectral Water Quality Monitoring & Forensic Anomaly Reporting

Generates professional PDF incident reports for environmental agencies
using the fpdf2 library with built-in PDF fonts only (Helvetica, Courier, Times).

Usage
-----
    from pdf_report import generate_incident_report, generate_quick_summary_pdf

    generate_incident_report(detections, forensic_analyses, roi_info, output_path)
    generate_quick_summary_pdf(stats, roi_info, output_path)
"""

import os
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from config import INFER, ROI, DASHBOARD

# ─────────────────────────────────────────────────
# Theme colours (R, G, B)
# ─────────────────────────────────────────────────
COLOR_HEADER_BG   = (15, 25, 55)
COLOR_HEADER_FG   = (255, 255, 255)
COLOR_CRITICAL    = (200, 50, 50)
COLOR_HIGH        = (230, 150, 30)
COLOR_WARNING     = (220, 200, 50)
COLOR_MONITOR     = (60, 160, 220)
COLOR_BODY_TEXT   = (30, 30, 30)
COLOR_MUTED       = (120, 120, 120)
COLOR_TABLE_HEADER = (20, 40, 80)
COLOR_TABLE_ROW_A = (240, 245, 255)
COLOR_TABLE_ROW_B = (255, 255, 255)
COLOR_ACCENT_LINE = (60, 160, 220)
COLOR_COVER_BG    = (10, 18, 42)
COLOR_COVER_ACCENT = (40, 180, 220)

SEVERITY_COLORS = {
    "CRITICAL": COLOR_CRITICAL,
    "HIGH":     COLOR_HIGH,
    "WARNING":  COLOR_WARNING,
    "MONITOR":  COLOR_MONITOR,
}

SEVERITY_ORDER = ["CRITICAL", "HIGH", "WARNING", "MONITOR"]

TIMESTAMP_FMT = "%Y-%m-%d %H:%M:%S UTC"


# ─────────────────────────────────────────────────
# Custom PDF class with automatic footer
# ─────────────────────────────────────────────────

class AquaSentinelPDF(FPDF):
    """FPDF subclass that adds a consistent footer to every page."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.generation_timestamp = datetime.utcnow().strftime(TIMESTAMP_FMT)
        self._skip_footer = False

    def footer(self):
        if self._skip_footer:
            return
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*COLOR_MUTED)
        self.cell(0, 4, f"Generated by Aqua-Sentinel AI  |  {self.generation_timestamp}", align="L")
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="R", new_x="LMARGIN", new_y="NEXT")


# ─────────────────────────────────────────────────
# Helper functions
# ─────────────────────────────────────────────────

def _add_header(pdf: FPDF, title: str) -> None:
    """Add a styled section header with a coloured background bar."""
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_fill_color(*COLOR_HEADER_BG)
    pdf.set_text_color(*COLOR_HEADER_FG)
    pdf.cell(0, 10, f"  {title}", fill=True, new_x="LMARGIN", new_y="NEXT")
    # Accent underline
    pdf.set_draw_color(*COLOR_ACCENT_LINE)
    pdf.set_line_width(0.6)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(4)
    # Reset text colour
    pdf.set_text_color(*COLOR_BODY_TEXT)


def _add_severity_badge(pdf: FPDF, severity: str) -> None:
    """Render a small coloured severity indicator inline."""
    severity_upper = severity.upper()
    color = SEVERITY_COLORS.get(severity_upper, COLOR_MUTED)
    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    badge_width = pdf.get_string_width(f" {severity_upper} ") + 4
    pdf.cell(badge_width, 6, f" {severity_upper} ", fill=True)
    pdf.set_text_color(*COLOR_BODY_TEXT)


def _add_table_row(pdf: FPDF, data: list, widths: list, colors: list = None) -> None:
    """
    Render a single table row with optional per-cell background colours.

    Parameters
    ----------
    pdf    : FPDF instance
    data   : list of cell text values
    widths : list of column widths (mm)
    colors : optional list of (R, G, B) tuples or None per cell
    """
    row_height = 7
    x_start = pdf.get_x()
    y_start = pdf.get_y()

    for i, (text, w) in enumerate(zip(data, widths)):
        if colors and colors[i] is not None:
            pdf.set_fill_color(*colors[i])
            fill = True
        else:
            fill = False
        pdf.set_xy(x_start + sum(widths[:i]), y_start)
        pdf.cell(w, row_height, str(text), border=1, fill=fill)

    pdf.set_xy(x_start, y_start + row_height)


def _severity_rank(severity: str) -> int:
    """Return a numeric rank for severity (lower = more severe)."""
    try:
        return SEVERITY_ORDER.index(severity.upper())
    except ValueError:
        return 99


def _safe_text(text) -> str:
    """Ensure text is a string suitable for PDF rendering."""
    if text is None:
        return "N/A"
    return str(text)


def _check_page_space(pdf: FPDF, needed_mm: float) -> None:
    """Add a new page if remaining space is less than needed_mm."""
    if pdf.get_y() + needed_mm > pdf.h - 20:
        pdf.add_page()


# ─────────────────────────────────────────────────
# Severity breakdown helpers
# ─────────────────────────────────────────────────

def _count_severities(detections: list, forensic_analyses: list) -> dict:
    """Count detections by severity. Uses forensic analysis when available."""
    counts = {s: 0 for s in SEVERITY_ORDER}

    # Build a lookup from forensic analyses
    forensic_severity_map = {}
    for fa in forensic_analyses:
        chip = fa.get("chip", fa.get("detection_id", ""))
        sev = fa.get("severity", "MONITOR").upper()
        forensic_severity_map[chip] = sev

    for det in detections:
        chip = det.get("chip", "")
        sev = forensic_severity_map.get(chip, "MONITOR").upper()
        if sev in counts:
            counts[sev] += 1
        else:
            counts["MONITOR"] += 1

    return counts


def _overall_assessment(severity_counts: dict) -> str:
    """Return a human-readable overall water quality assessment."""
    if severity_counts.get("CRITICAL", 0) > 0:
        return "CRITICAL -- Immediate intervention required. Multiple severe anomalies detected."
    if severity_counts.get("HIGH", 0) > 0:
        return "POOR -- Significant anomalies detected. Investigation and corrective action recommended."
    if severity_counts.get("WARNING", 0) > 0:
        return "FAIR -- Moderate anomalies observed. Continued monitoring and preventive measures advised."
    if severity_counts.get("MONITOR", 0) > 0:
        return "ACCEPTABLE -- Minor anomalies detected. Routine monitoring sufficient."
    return "GOOD -- No anomalies detected. Water quality within acceptable parameters."


def _find_critical_hotspot(detections: list, forensic_analyses: list) -> dict:
    """Find the GPS location of the most critical detection."""
    forensic_map = {}
    for fa in forensic_analyses:
        chip = fa.get("chip", fa.get("detection_id", ""))
        forensic_map[chip] = fa

    best = None
    best_rank = 99
    for det in detections:
        chip = det.get("chip", "")
        fa = forensic_map.get(chip, {})
        sev = fa.get("severity", "MONITOR")
        rank = _severity_rank(sev)
        conf = det.get("confidence", 0)
        if rank < best_rank or (rank == best_rank and best and conf > best.get("confidence", 0)):
            best_rank = rank
            best = det
    return best or {}


# ─────────────────────────────────────────────────
# Cover page
# ─────────────────────────────────────────────────

def _add_cover_page(pdf: AquaSentinelPDF, roi_info: dict) -> None:
    """Render the cover page of the incident report."""
    pdf._skip_footer = True
    pdf.add_page()

    # Dark background fill
    pdf.set_fill_color(*COLOR_COVER_BG)
    pdf.rect(0, 0, pdf.w, pdf.h, "F")

    # Top accent bar
    pdf.set_fill_color(*COLOR_COVER_ACCENT)
    pdf.rect(0, 0, pdf.w, 4, "F")

    # Classification banner at top
    pdf.set_y(15)
    pdf.set_font("Courier", "B", 9)
    pdf.set_text_color(200, 60, 60)
    pdf.cell(0, 6, "CONFIDENTIAL -- FOR AUTHORIZED PERSONNEL ONLY", align="C",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(25)

    # Title
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*COLOR_COVER_ACCENT)
    pdf.cell(0, 14, "AQUA-SENTINEL AI", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Divider
    pdf.set_draw_color(*COLOR_COVER_ACCENT)
    pdf.set_line_width(0.8)
    mid_x = pdf.w / 2
    pdf.line(mid_x - 60, pdf.get_y(), mid_x + 60, pdf.get_y())
    pdf.ln(6)

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 12, "INCIDENT REPORT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    pdf.set_font("Helvetica", "", 13)
    pdf.set_text_color(180, 200, 220)
    pdf.cell(0, 8, "Water Quality Anomaly Assessment", align="C",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)

    # Water body information block
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(160, 180, 200)

    water_body = roi_info.get("water_body", roi_info.get("name", "Unknown"))
    state = roi_info.get("state", "Unknown")
    city = roi_info.get("city", "Unknown")
    now = datetime.utcnow()

    info_lines = [
        ("Water Body", water_body),
        ("Location", f"{city}, {state}"),
        ("Report Date", now.strftime("%B %d, %Y")),
        ("Report Time", now.strftime("%H:%M:%S UTC")),
        ("Water Type", roi_info.get("water_type", "N/A").capitalize()),
        ("Bounding Box",
         f"{roi_info.get('lat_min', 'N/A')}N, {roi_info.get('lon_min', 'N/A')}E  to  "
         f"{roi_info.get('lat_max', 'N/A')}N, {roi_info.get('lon_max', 'N/A')}E"),
    ]

    for label, value in info_lines:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(100, 140, 180)
        pdf.cell(55, 8, f"{label}:", align="R")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(220, 230, 240)
        pdf.cell(0, 8, f"  {value}", new_x="LMARGIN", new_y="NEXT")

    # Bottom accent bar
    pdf.set_fill_color(*COLOR_COVER_ACCENT)
    pdf.rect(0, pdf.h - 4, pdf.w, 4, "F")

    # System identifier at bottom
    pdf.set_y(pdf.h - 20)
    pdf.set_font("Courier", "", 7)
    pdf.set_text_color(80, 100, 120)
    pdf.cell(0, 4, f"Report ID: AQSI-{now.strftime('%Y%m%d%H%M%S')}  |  "
             f"System: {DASHBOARD.get('title', 'Aqua-Sentinel AI')}  |  "
             f"{DASHBOARD.get('subtitle', '')}",
             align="C", new_x="LMARGIN", new_y="NEXT")

    pdf._skip_footer = False


# ─────────────────────────────────────────────────
# Executive summary page
# ─────────────────────────────────────────────────

def _add_executive_summary(
    pdf: AquaSentinelPDF,
    detections: list,
    forensic_analyses: list,
    roi_info: dict,
) -> None:
    """Render the executive summary page."""
    pdf.add_page()
    _add_header(pdf, "EXECUTIVE SUMMARY")
    pdf.ln(2)

    sev_counts = _count_severities(detections, forensic_analyses)
    total = len(detections)
    assessment = _overall_assessment(sev_counts)
    hotspot = _find_critical_hotspot(detections, forensic_analyses)

    # Total anomalies
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(55, 8, "Total Anomalies Detected:")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(*COLOR_CRITICAL if sev_counts.get("CRITICAL", 0) > 0 else COLOR_BODY_TEXT)
    pdf.cell(0, 8, str(total), new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*COLOR_BODY_TEXT)
    pdf.ln(2)

    # Severity breakdown
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Severity Breakdown:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)

    for sev in SEVERITY_ORDER:
        count = sev_counts.get(sev, 0)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(10, 7, "")
        _add_severity_badge(pdf, sev)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(5, 6, "")
        pdf.cell(0, 6, f"{count} detection(s)", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Most critical hotspot
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Most Critical Hotspot:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    lat = hotspot.get("centre_lat")
    lon = hotspot.get("centre_lon")
    if lat is not None and lon is not None:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"GPS Coordinates: {lat:.6f} N, {lon:.6f} E",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Chip: {hotspot.get('chip', 'N/A')}  |  "
                 f"Confidence: {hotspot.get('confidence', 0):.1%}",
                 new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, "No GPS-referenced detections available.",
                 new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Overall assessment
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Overall Water Quality Assessment:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(10, 7, "")
    pdf.multi_cell(0, 7, assessment, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Region summary
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Monitored Region:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    water_body = roi_info.get("water_body", roi_info.get("name", "Unknown"))
    city = roi_info.get("city", "Unknown")
    state = roi_info.get("state", "Unknown")
    pdf.cell(10, 7, "")
    pdf.cell(0, 7, f"{water_body}, {city}, {state}", new_x="LMARGIN", new_y="NEXT")


# ─────────────────────────────────────────────────
# Forensic analysis section
# ─────────────────────────────────────────────────

def _add_forensic_analysis_section(
    pdf: AquaSentinelPDF,
    forensic_analyses: list,
) -> None:
    """Render the forensic analysis section with per-detection verdicts."""
    pdf.add_page()
    _add_header(pdf, "FORENSIC ANALYSIS")
    pdf.ln(2)

    if not forensic_analyses:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "No forensic analyses available for this report.",
                 new_x="LMARGIN", new_y="NEXT")
        return

    for idx, fa in enumerate(forensic_analyses):
        _check_page_space(pdf, 60)

        # Analysis header
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(230, 235, 245)
        chip = fa.get("chip", fa.get("detection_id", f"Analysis-{idx + 1}"))
        pdf.cell(0, 8, f"  Analysis #{idx + 1}  --  {chip}", fill=True,
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Verdict
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(30, 7, "Verdict:")
        pdf.set_font("Helvetica", "", 10)
        verdict = fa.get("verdict", "No verdict available")
        pdf.multi_cell(0, 7, _safe_text(verdict), new_x="LMARGIN", new_y="NEXT")

        # Severity badge
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(30, 7, "Severity:")
        severity = fa.get("severity", "MONITOR")
        _add_severity_badge(pdf, severity)
        pdf.ln(8)

        # Confidence
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(30, 7, "Confidence:")
        pdf.set_font("Helvetica", "", 10)
        confidence = fa.get("confidence", fa.get("confidence_score", None))
        if confidence is not None:
            if isinstance(confidence, (int, float)) and confidence <= 1.0:
                pdf.cell(0, 7, f"{confidence:.1%}", new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.cell(0, 7, f"{confidence}", new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.cell(0, 7, "N/A", new_x="LMARGIN", new_y="NEXT")

        # Reasoning chain
        reasoning = fa.get("reasoning", fa.get("reasoning_chain", []))
        if reasoning:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, "Reasoning Chain:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            if isinstance(reasoning, list):
                for step_num, step in enumerate(reasoning, 1):
                    _check_page_space(pdf, 10)
                    pdf.cell(10, 6, "")
                    pdf.multi_cell(0, 6, f"{step_num}. {_safe_text(step)}",
                                   new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.cell(10, 6, "")
                pdf.multi_cell(0, 6, _safe_text(reasoning),
                               new_x="LMARGIN", new_y="NEXT")

        # Recommended action
        action = fa.get("recommended_action", fa.get("action", None))
        if action:
            _check_page_space(pdf, 12)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 7, "Recommended Action:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(10, 6, "")
            pdf.multi_cell(0, 6, _safe_text(action), new_x="LMARGIN", new_y="NEXT")

        pdf.ln(4)

        # Separator between analyses
        if idx < len(forensic_analyses) - 1:
            pdf.set_draw_color(*COLOR_MUTED)
            pdf.set_line_width(0.2)
            y = pdf.get_y()
            pdf.line(pdf.l_margin + 10, y, pdf.w - pdf.r_margin - 10, y)
            pdf.ln(4)


# ─────────────────────────────────────────────────
# Detection log table
# ─────────────────────────────────────────────────

def _add_detection_log_table(
    pdf: AquaSentinelPDF,
    detections: list,
    forensic_analyses: list,
) -> None:
    """Render the detection log as a colour-coded table."""
    pdf.add_page()
    _add_header(pdf, "DETECTION LOG")
    pdf.ln(2)

    if not detections:
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, "No detections recorded.", new_x="LMARGIN", new_y="NEXT")
        return

    # Build forensic severity map
    forensic_map = {}
    for fa in forensic_analyses:
        chip = fa.get("chip", fa.get("detection_id", ""))
        forensic_map[chip] = fa

    # Column definitions:  #, Location, Type, Confidence, Severity, GPS
    col_widths = [10, 40, 35, 25, 25, 55]
    headers = ["#", "Location", "Type", "Conf.", "Severity", "GPS"]

    # Table header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*COLOR_TABLE_HEADER)
    pdf.set_text_color(255, 255, 255)
    header_colors = [COLOR_TABLE_HEADER] * len(headers)
    _add_table_row(pdf, headers, col_widths, header_colors)
    pdf.set_text_color(*COLOR_BODY_TEXT)

    # Table rows
    pdf.set_font("Helvetica", "", 7)
    for idx, det in enumerate(detections):
        _check_page_space(pdf, 10)

        # Re-render header on new page
        if pdf.get_y() <= pdf.t_margin + 2:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(255, 255, 255)
            _add_table_row(pdf, headers, col_widths, header_colors)
            pdf.set_text_color(*COLOR_BODY_TEXT)
            pdf.set_font("Helvetica", "", 7)

        chip = det.get("chip", "N/A")
        det_class = det.get("class", "N/A")
        conf = det.get("confidence", 0)
        lat = det.get("centre_lat")
        lon = det.get("centre_lon")

        fa = forensic_map.get(chip, {})
        severity = fa.get("severity", "MONITOR").upper()

        gps_str = f"{lat:.4f}, {lon:.4f}" if lat is not None and lon is not None else "N/A"

        # Severity colour for the severity cell
        sev_color = SEVERITY_COLORS.get(severity, COLOR_MUTED)
        # Lighter version for cell background
        sev_bg = tuple(min(255, int(c * 0.3 + 255 * 0.7)) for c in sev_color)

        # Alternating row background
        row_bg = COLOR_TABLE_ROW_A if idx % 2 == 0 else COLOR_TABLE_ROW_B
        row_colors = [row_bg, row_bg, row_bg, row_bg, sev_bg, row_bg]

        row_data = [
            str(idx + 1),
            chip[:20] if len(chip) > 20 else chip,
            det_class,
            f"{conf:.1%}",
            severity,
            gps_str,
        ]

        _add_table_row(pdf, row_data, col_widths, row_colors)

    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*COLOR_MUTED)
    pdf.cell(0, 6, f"Total detections: {len(detections)}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*COLOR_BODY_TEXT)


# ─────────────────────────────────────────────────
# Spectral analysis summary
# ─────────────────────────────────────────────────

def _add_spectral_analysis(
    pdf: AquaSentinelPDF,
    detections: list,
    forensic_analyses: list,
) -> None:
    """Render the spectral analysis summary section."""
    pdf.add_page()
    _add_header(pdf, "SPECTRAL ANALYSIS SUMMARY")
    pdf.ln(2)

    # Collect spectral data from forensic analyses
    ndwi_values = []
    chlorophyll_values = []
    turbidity_values = []
    water_quality_scores = []

    for fa in forensic_analyses:
        spectral = fa.get("spectral", fa.get("spectral_data", {}))
        if isinstance(spectral, dict):
            if "ndwi" in spectral:
                ndwi_values.append(spectral["ndwi"])
            if "chlorophyll" in spectral or "chlorophyll_a" in spectral:
                chlorophyll_values.append(
                    spectral.get("chlorophyll", spectral.get("chlorophyll_a", 0))
                )
            if "turbidity" in spectral:
                turbidity_values.append(spectral["turbidity"])
            if "water_quality_score" in spectral:
                water_quality_scores.append(spectral["water_quality_score"])

    # NDWI statistics
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "NDWI (Normalized Difference Water Index)", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if ndwi_values:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Mean:  {sum(ndwi_values) / len(ndwi_values):.4f}",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Min:   {min(ndwi_values):.4f}    Max: {max(ndwi_values):.4f}",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Samples: {len(ndwi_values)}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, "No NDWI data available from current analysis.",
                 new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Chlorophyll-a levels
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Chlorophyll-a Levels", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if chlorophyll_values:
        mean_chl = sum(chlorophyll_values) / len(chlorophyll_values)
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Mean:  {mean_chl:.4f}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Min:   {min(chlorophyll_values):.4f}    "
                 f"Max: {max(chlorophyll_values):.4f}",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        status = "ELEVATED -- Possible algal bloom" if mean_chl > 1.8 else "Within normal range"
        pdf.cell(0, 7, f"Status: {status}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, "No chlorophyll-a data available from current analysis.",
                 new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Turbidity readings
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Turbidity Readings", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if turbidity_values:
        mean_turb = sum(turbidity_values) / len(turbidity_values)
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Mean:  {mean_turb:.4f}", new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, f"Min:   {min(turbidity_values):.4f}    "
                 f"Max: {max(turbidity_values):.4f}",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.cell(10, 7, "")
        status = "HIGH -- Water clarity compromised" if mean_turb > 0.15 else "Acceptable levels"
        pdf.cell(0, 7, f"Status: {status}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, "No turbidity data available from current analysis.",
                 new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Water quality score
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Water Quality Score", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    if water_quality_scores:
        avg_score = sum(water_quality_scores) / len(water_quality_scores)
        pdf.cell(10, 7, "")
        pdf.set_font("Helvetica", "B", 12)
        if avg_score >= 80:
            pdf.set_text_color(40, 160, 80)
        elif avg_score >= 50:
            pdf.set_text_color(*COLOR_WARNING)
        else:
            pdf.set_text_color(*COLOR_CRITICAL)
        pdf.cell(0, 7, f"{avg_score:.1f} / 100", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*COLOR_BODY_TEXT)
    else:
        pdf.cell(10, 7, "")
        pdf.cell(0, 7, "Water quality score not computed for this analysis cycle.",
                 new_x="LMARGIN", new_y="NEXT")


# ─────────────────────────────────────────────────
# Recommendations page
# ─────────────────────────────────────────────────

def _add_recommendations(
    pdf: AquaSentinelPDF,
    detections: list,
    forensic_analyses: list,
) -> None:
    """Render prioritised recommendations and follow-up timeline."""
    pdf.add_page()
    _add_header(pdf, "RECOMMENDATIONS")
    pdf.ln(2)

    sev_counts = _count_severities(detections, forensic_analyses)

    # Collect unique recommended actions from forensic analyses
    actions_by_severity = {s: [] for s in SEVERITY_ORDER}
    for fa in forensic_analyses:
        sev = fa.get("severity", "MONITOR").upper()
        action = fa.get("recommended_action", fa.get("action", None))
        if action and sev in actions_by_severity:
            if action not in actions_by_severity[sev]:
                actions_by_severity[sev].append(action)

    # Prioritised action list
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, "Prioritised Action Items:", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    action_num = 0
    for sev in SEVERITY_ORDER:
        for action in actions_by_severity[sev]:
            action_num += 1
            _check_page_space(pdf, 14)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(8, 7, "")
            _add_severity_badge(pdf, sev)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(5, 6, "")
            pdf.multi_cell(0, 6, f"{action_num}. {_safe_text(action)}",
                           new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    if action_num == 0:
        # Generate default recommendations based on severity counts
        default_actions = []
        if sev_counts.get("CRITICAL", 0) > 0:
            default_actions.append(
                ("CRITICAL", "Dispatch emergency response team to identified hotspot(s). "
                 "Initiate water sampling within 24 hours.")
            )
            default_actions.append(
                ("CRITICAL", "Notify relevant environmental regulatory authorities immediately.")
            )
        if sev_counts.get("HIGH", 0) > 0:
            default_actions.append(
                ("HIGH", "Conduct on-site investigation at flagged locations within 48 hours.")
            )
            default_actions.append(
                ("HIGH", "Review upstream industrial discharge permits and compliance records.")
            )
        if sev_counts.get("WARNING", 0) > 0:
            default_actions.append(
                ("WARNING", "Increase monitoring frequency for affected zones to daily intervals.")
            )
            default_actions.append(
                ("WARNING", "Cross-reference with recent weather events and agricultural runoff patterns.")
            )
        if sev_counts.get("MONITOR", 0) > 0:
            default_actions.append(
                ("MONITOR", "Continue routine satellite surveillance at standard intervals.")
            )

        if not default_actions:
            default_actions.append(
                ("MONITOR", "No anomalies detected. Maintain current monitoring schedule.")
            )

        for i, (sev, action) in enumerate(default_actions, 1):
            _check_page_space(pdf, 14)
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(8, 7, "")
            _add_severity_badge(pdf, sev)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(5, 6, "")
            pdf.multi_cell(0, 6, f"{i}. {action}", new_x="LMARGIN", new_y="NEXT")
            pdf.ln(1)

    # Follow-up timeline
    pdf.ln(6)
    _check_page_space(pdf, 50)
    _add_header(pdf, "SUGGESTED FOLLOW-UP TIMELINE")
    pdf.ln(2)

    has_critical = sev_counts.get("CRITICAL", 0) > 0
    has_high = sev_counts.get("HIGH", 0) > 0
    has_warning = sev_counts.get("WARNING", 0) > 0

    timeline = []
    if has_critical:
        timeline.append(("0 - 24 hours", "CRITICAL",
                         "Emergency field verification and water sampling at critical hotspots."))
        timeline.append(("24 - 48 hours", "CRITICAL",
                         "Laboratory analysis of collected samples. "
                         "Notify regulatory bodies with preliminary findings."))
    if has_high:
        timeline.append(("48 - 72 hours", "HIGH",
                         "On-site investigation of high-severity zones. "
                         "Identify potential discharge sources."))
    if has_critical or has_high:
        timeline.append(("1 week", "HIGH",
                         "Follow-up satellite acquisition for change detection analysis."))
    if has_warning:
        timeline.append(("1 - 2 weeks", "WARNING",
                         "Expanded monitoring of warning-level areas. "
                         "Review historical trends."))
    timeline.append(("30 days", "MONITOR",
                     "Comprehensive re-assessment with updated satellite imagery. "
                     "Generate comparative report."))
    timeline.append(("Quarterly", "MONITOR",
                     "Routine satellite surveillance cycle and compliance review."))

    col_widths_tl = [35, 25, 130]
    headers_tl = ["Timeframe", "Priority", "Action"]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(*COLOR_TABLE_HEADER)
    pdf.set_text_color(255, 255, 255)
    _add_table_row(pdf, headers_tl, col_widths_tl,
                   [COLOR_TABLE_HEADER] * len(headers_tl))
    pdf.set_text_color(*COLOR_BODY_TEXT)

    pdf.set_font("Helvetica", "", 8)
    for idx, (timeframe, priority, action) in enumerate(timeline):
        _check_page_space(pdf, 10)
        sev_color = SEVERITY_COLORS.get(priority, COLOR_MUTED)
        sev_bg = tuple(min(255, int(c * 0.3 + 255 * 0.7)) for c in sev_color)
        row_bg = COLOR_TABLE_ROW_A if idx % 2 == 0 else COLOR_TABLE_ROW_B
        row_colors = [row_bg, sev_bg, row_bg]
        _add_table_row(pdf, [timeframe, priority, action[:75]], col_widths_tl, row_colors)


# ─────────────────────────────────────────────────
# Main report generator
# ─────────────────────────────────────────────────

def generate_incident_report(
    detections: list,
    forensic_analyses: list,
    roi_info: dict = None,
    output_path: str = None,
    detection_images: list = None,
) -> str:
    """
    Generate a complete PDF incident report.

    Parameters
    ----------
    detections : list[dict]
        List of detection records. Each dict should contain keys such as
        'chip', 'confidence', 'class', 'centre_lat', 'centre_lon', 'bbox_px',
        'timestamp'.
    forensic_analyses : list[dict]
        List of forensic analysis records. Each dict may contain keys such as
        'chip'/'detection_id', 'verdict', 'severity', 'confidence',
        'reasoning'/'reasoning_chain', 'recommended_action', 'spectral'.
    roi_info : dict, optional
        Region of interest information. Defaults to config.ROI.
    output_path : str, optional
        Path for the output PDF. Defaults to INFER["report_pdf"].
    detection_images : list[str], optional
        List of paths to detection images (currently reserved for future use).

    Returns
    -------
    str
        The absolute path to the generated PDF report.
    """
    if roi_info is None:
        roi_info = ROI
    if output_path is None:
        output_path = INFER["report_pdf"]

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if detections is None:
        detections = []
    if forensic_analyses is None:
        forensic_analyses = []

    pdf = AquaSentinelPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # 1. Cover page
    _add_cover_page(pdf, roi_info)

    # 2. Executive summary
    _add_executive_summary(pdf, detections, forensic_analyses, roi_info)

    # 3. Forensic analysis
    _add_forensic_analysis_section(pdf, forensic_analyses)

    # 4. Detection log table
    _add_detection_log_table(pdf, detections, forensic_analyses)

    # 5. Spectral analysis summary
    _add_spectral_analysis(pdf, detections, forensic_analyses)

    # 6. Recommendations
    _add_recommendations(pdf, detections, forensic_analyses)

    # Write PDF
    pdf.output(str(output_path))

    print(f"[PDF] Incident report generated -> {output_path}")
    return str(output_path.resolve())


# ─────────────────────────────────────────────────
# Quick summary PDF
# ─────────────────────────────────────────────────

def generate_quick_summary_pdf(
    stats: dict,
    roi_info: dict = None,
    output_path: str = None,
) -> str:
    """
    Generate a short 1-2 page quick summary PDF.

    Parameters
    ----------
    stats : dict
        Summary statistics. Expected keys:
        - 'total_detections' : int
        - 'severity_counts'  : dict mapping severity -> count
        - 'avg_confidence'   : float
        - 'affected_tiles'   : int
        - 'gps_hotspots'     : int
        - 'top_class'        : str  (most frequent anomaly type)
        - 'assessment'       : str  (overall assessment text)
        - 'generated_at'     : str  (timestamp)
    roi_info : dict, optional
        Region of interest information. Defaults to config.ROI.
    output_path : str, optional
        Path for the output PDF.

    Returns
    -------
    str
        The absolute path to the generated PDF.
    """
    if roi_info is None:
        roi_info = ROI
    if output_path is None:
        output_path = str(
            Path(INFER["report_pdf"]).parent / "quick_summary.pdf"
        )

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    pdf = AquaSentinelPDF(orientation="P", unit="mm", format="A4")
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title bar
    pdf.set_fill_color(*COLOR_HEADER_BG)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 14, "  AQUA-SENTINEL AI  --  QUICK SUMMARY", fill=True,
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    # Accent line
    pdf.set_draw_color(*COLOR_ACCENT_LINE)
    pdf.set_line_width(0.8)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(6)

    # Region info
    pdf.set_text_color(*COLOR_BODY_TEXT)
    pdf.set_font("Helvetica", "B", 10)
    water_body = roi_info.get("water_body", roi_info.get("name", "Unknown"))
    city = roi_info.get("city", "Unknown")
    state = roi_info.get("state", "Unknown")
    pdf.cell(0, 7, f"Region: {water_body}, {city}, {state}", new_x="LMARGIN", new_y="NEXT")
    generated_at = stats.get("generated_at", datetime.utcnow().strftime(TIMESTAMP_FMT))
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 7, f"Generated: {generated_at}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Key metrics
    _add_header(pdf, "KEY METRICS")
    pdf.ln(2)

    total = stats.get("total_detections", 0)
    avg_conf = stats.get("avg_confidence", 0)
    tiles = stats.get("affected_tiles", 0)
    gps = stats.get("gps_hotspots", 0)
    top_class = stats.get("top_class", "N/A")

    metrics = [
        ("Total Detections", str(total)),
        ("Average Confidence", f"{avg_conf:.1%}" if isinstance(avg_conf, float) else str(avg_conf)),
        ("Affected Tiles", str(tiles)),
        ("GPS-Located Hotspots", str(gps)),
        ("Most Frequent Anomaly", top_class),
    ]

    pdf.set_font("Helvetica", "", 10)
    for label, value in metrics:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(55, 7, f"{label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # Severity breakdown
    sev_counts = stats.get("severity_counts", {})
    if sev_counts:
        _add_header(pdf, "SEVERITY BREAKDOWN")
        pdf.ln(2)
        for sev in SEVERITY_ORDER:
            count = sev_counts.get(sev, sev_counts.get(sev.lower(), 0))
            if count > 0 or True:  # Show all severities
                pdf.cell(10, 7, "")
                _add_severity_badge(pdf, sev)
                pdf.set_font("Helvetica", "", 10)
                pdf.cell(5, 6, "")
                pdf.cell(0, 6, f"{count} detection(s)", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Assessment
    assessment = stats.get("assessment", "")
    if assessment:
        _add_header(pdf, "OVERALL ASSESSMENT")
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, assessment, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Classification notice
    pdf.ln(6)
    pdf.set_font("Courier", "B", 8)
    pdf.set_text_color(180, 60, 60)
    pdf.cell(0, 6, "CONFIDENTIAL -- FOR AUTHORIZED PERSONNEL ONLY", align="C",
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*COLOR_BODY_TEXT)

    # Write PDF
    pdf.output(str(output_path))
    print(f"[PDF] Quick summary generated -> {output_path}")
    return str(output_path.resolve())


# ─────────────────────────────────────────────────
# CLI entry point for testing
# ─────────────────────────────────────────────────

if __name__ == "__main__":
    # Generate a sample report with demo data for testing
    sample_detections = [
        {
            "chip": "tile_001_thermal",
            "confidence": 0.92,
            "class": "thermal_plume",
            "bbox_px": [120, 80, 340, 260],
            "centre_lat": 30.8912,
            "centre_lon": 75.8345,
            "timestamp": datetime.utcnow().isoformat(),
        },
        {
            "chip": "tile_002_spectral",
            "confidence": 0.78,
            "class": "algal_bloom",
            "bbox_px": [200, 150, 450, 380],
            "centre_lat": 30.8856,
            "centre_lon": 75.8401,
            "timestamp": datetime.utcnow().isoformat(),
        },
        {
            "chip": "tile_003_turbid",
            "confidence": 0.65,
            "class": "turbidity_spike",
            "bbox_px": [50, 300, 280, 500],
            "centre_lat": 30.8934,
            "centre_lon": 75.8278,
            "timestamp": datetime.utcnow().isoformat(),
        },
    ]

    sample_forensics = [
        {
            "chip": "tile_001_thermal",
            "verdict": "Likely Untreated Industrial Coolant Discharge",
            "severity": "CRITICAL",
            "confidence": 0.92,
            "reasoning": [
                "Thermal signature detected at 325.4K, exceeding baseline by 12.3K.",
                "Hotspot located within 350m of registered industrial zone.",
                "Discharge pattern consistent with continuous-flow coolant release.",
                "No natural geothermal activity recorded in this region.",
            ],
            "recommended_action": (
                "Dispatch emergency response team immediately. "
                "Collect water samples at discharge point and 500m downstream. "
                "Notify Punjab Pollution Control Board."
            ),
            "spectral": {
                "ndwi": 0.42,
                "chlorophyll": 1.2,
                "turbidity": 0.08,
                "water_quality_score": 35.0,
            },
        },
        {
            "chip": "tile_002_spectral",
            "verdict": "Eutrophication due to Nutrient (Fertilizer) Overload",
            "severity": "WARNING",
            "confidence": 0.78,
            "reasoning": [
                "Elevated chlorophyll-a levels detected (ratio 2.1).",
                "Green spectral band shows abnormal reflectance increase.",
                "Surrounding land use includes agricultural fields.",
                "Seasonal alignment with fertilizer application period.",
            ],
            "recommended_action": (
                "Monitor algal bloom progression over next 7 days. "
                "Assess nutrient loading from upstream agricultural runoff."
            ),
            "spectral": {
                "ndwi": 0.35,
                "chlorophyll": 2.1,
                "turbidity": 0.11,
                "water_quality_score": 58.0,
            },
        },
        {
            "chip": "tile_003_turbid",
            "verdict": "Probable Siltation or Construction Runoff",
            "severity": "WARNING",
            "confidence": 0.65,
            "reasoning": [
                "High turbidity index (0.22) detected in localised zone.",
                "Brown coloration signature present in RGB composite.",
                "Active construction site identified 200m upstream.",
            ],
            "recommended_action": (
                "Inspect upstream construction activity for sediment control compliance. "
                "Request installation of silt barriers if not present."
            ),
            "spectral": {
                "ndwi": 0.28,
                "chlorophyll": 0.9,
                "turbidity": 0.22,
                "water_quality_score": 62.0,
            },
        },
    ]

    print("=" * 60)
    print("  Aqua-Sentinel AI -- PDF Report Generator (Demo)")
    print("=" * 60)

    # Full incident report
    report_path = generate_incident_report(
        detections=sample_detections,
        forensic_analyses=sample_forensics,
        roi_info=ROI,
    )
    print(f"\n  Full report:    {report_path}")

    # Quick summary
    sample_stats = {
        "total_detections": len(sample_detections),
        "severity_counts": {"CRITICAL": 1, "HIGH": 0, "WARNING": 2, "MONITOR": 0},
        "avg_confidence": 0.783,
        "affected_tiles": 3,
        "gps_hotspots": 3,
        "top_class": "thermal_plume",
        "assessment": (
            "FAIR -- Moderate anomalies observed including one critical thermal discharge. "
            "Immediate investigation recommended for the industrial zone hotspot. "
            "Continued monitoring advised for algal bloom and siltation areas."
        ),
        "generated_at": datetime.utcnow().strftime(TIMESTAMP_FMT),
    }

    summary_path = generate_quick_summary_pdf(
        stats=sample_stats,
        roi_info=ROI,
    )
    print(f"  Quick summary:  {summary_path}")
    print("\n" + "=" * 60)
